### PR TITLE
Comparison between simulated and experimental specular profile

### LINKED ISSUE #1: Comparison between simulated and experimental specular profile
Given an experimental profile and resolution settings, calculate the Chi-square using a simulated profile

### PR DESCRIPTION
**Pull request by jmborr**
Fixes #1

### CODE REVIEW

**Comment by jmborr** [comment]
@AndreiSavici The comparison uses Mantid fitting, but maybe we can use `lmfit` instead. It's a pure python package and we won't need to wait for Jiao to build appropriate Mantid packages in conda to test this. What do you think?

**Comment by AndreiSavici** [comment]
Go for it. `lmfit` sounds good

**Comment by stuartcampbell** [comment]
Lmfit is good, we use it a lot.... :)

**Comment by jmborr** [comment]
OK, `lmfit` it is

**Comment by AndreiSavici** [comment]
Since we are going to rewrite the whole fitting stuff, I think that you should move your code to some Fitting-Playground folder instead

**Comment by jmborr** [comment]
will do

**Pull request merged**
